#! /bin/bash

read -p "Enter a Number : " NUM
echo

  if [ $NUM -gt 100]
  then
    echo "We hav entered IF block"
    sleep 5
    echo "Your Number is greater than 100"
    echo 
    date

  fi 
  echo "Scrip execution completed successfully"

--------------------------------------------------------------------------------

  #! /bin/bash

read -p "Enter a Number : " NUM
echo

  if [ $NUM -gt 100]
  then
    echo "We hav entered IF block"
    sleep 5
    echo "Your Number is greater than 100"
    echo 
    date
  else
  echo "Your number is less than 100"
  fi 
  echo "Scrip execution completed successfully"

  --------------------------------------------------------------------------------


  
 #! /bin/bash

 VALUE=$(ip addr show | grep -v LOOPBACK | grep -ic mtu)

   if [ $VALUE -eq 1 ]
    then
      echo "Found single active network interface"

  elif [ $VALUE -gt 1 ]
    then
      echo "Found multiple active network interface"

  else 
      echo "No active network interface"
fi
