#! /bin/bash

	for VAR1 in java .net python ruby php
	do 
		echo "Looping..."
		sleep 2
		echo ""
		echo "------------------------------------------------------"
		echo "				Value of VAR1 is $VAR1					"
		echo "------------------------------------------------------"
		echo ""
		date
	done

----------------------------------------------------------------------------------------------------------------------------

#! /bin/bash

USERS="Alpha Beta Gama"
	for USR in $USERS
		do
			sleep 2
			echo "------------------------------------------------------"
			echo "				Creating new user $USR				"
			echo "------------------------------------------------------"
			echo ""
			echo ""
			echo "------------------------------------------------------"
			echo "				Created! User Id: $USR					"
			echo "------------------------------------------------------"
			echo ""
			echo ""
    done




